# syntax of the user configuration
syntax_version: 0.1

ws:
  rosbuild:
    type: rosbuild
    dir: rosbuild_ws
    rosinstall:
      - uri: https://raw.github.com/utexas-bwi/segbot/master/rosinstall/segbot.rosinstall

  catkin:
    type: catkin
    dir: catkin_ws
    rosinstall:
      - git:
          local-name: segway_rmp
          uri: https://github.com/segwayrmp/segway-rmp-ros-pkg.git

  gazebo:
    type: generic
    dir: gazebo
    bash: |
      export GAZEBO_MODEL_PATH=@BASE_DIR@/gazebo/gazebo_models:${GAZEBO_MODEL_PATH}
    rosinstall:
      - hg:
          local-name: gazebo_models
          uri: https://bitbucket.org/osrf/gazebo_models
