# syntax of the user configuration
syntax_version: 0.1

# Taken from the default apt installation target
# /opt/ros/<ros_distro>
ros_distro: groovy

ws:
  rosbuild:
    type: rosbuild
    dir: ros/rosbuild_ws

  catkin:
    type: catkin
    dir: ros/catkin_ws

